const canvas=document.getElementById('orb');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
if(!gl){document.body.innerHTML='<p style="padding:24px">WebGL is required for the Hive Orb prototype.</p>';throw new Error('WebGL unavailable');}
const vs=`attribute vec3 p;attribute float e;uniform mat4 mvp;varying float v;void main(){v=e;gl_Position=mvp*vec4(p,1.0);}`;
const fs=`precision mediump float;varying float v;void main(){gl_FragColor=vec4(.05,.95,.32,.16+.84*v);}`;
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);return x}
const pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,vs));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);gl.useProgram(pr);
const verts=[];const golden=Math.PI*(3-Math.sqrt(5));const cells=720;
function addHex(nx,ny,nz,size,energy){let ax=-ny,ay=nx,az=0;const al=Math.hypot(ax,ay,az)||1;ax/=al;ay/=al;az/=al;let bx=ny*az-nz*ay,by=nz*ax-nx*az,bz=nx*ay-ny*ax;for(let j=0;j<6;j++){const a=Math.PI/6+j*Math.PI/3,b=Math.PI/6+(j+1)*Math.PI/3;const r1=1.002,r2=1.002;verts.push(nx*r1+size*(ax*Math.cos(a)+bx*Math.sin(a)),ny*r1+size*(ay*Math.cos(a)+by*Math.sin(a)),nz*r1+size*(az*Math.cos(a)+bz*Math.sin(a)),energy);verts.push(nx*r2+size*(ax*Math.cos(b)+bx*Math.sin(b)),ny*r2+size*(ay*Math.cos(b)+by*Math.sin(b)),nz*r2+size*(az*Math.cos(b)+bz*Math.sin(b)),energy);}}
for(let i=0;i<cells;i++){const y=1-(i/(cells-1))*2,r=Math.sqrt(1-y*y),th=golden*i;const x=r*Math.cos(th),z=r*Math.sin(th);addHex(x,y,z,.025,.25)}
const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);const P=gl.getAttribLocation(pr,'p'),A=gl.getAttribLocation(pr,'e');const M=gl.getUniformLocation(pr,'mvp');
let rx=.18,ry=0,drag=false,lx=0,voice=.15,impulse=0;
canvas.onpointerdown=e=>{drag=true;lx=e.clientX;impulse=1};canvas.onpointerup=()=>drag=false;canvas.onpointermove=e=>{if(drag){ry+=(e.clientX-lx)*.006;lx=e.clientX}};canvas.onclick=()=>{impulse=1};
function mat(){const a=rx,b=ry,c=Math.cos(a),s=Math.sin(a),d=Math.cos(b),f=Math.sin(b);return new Float32Array([d,0,-f,0,s*f,c,s*d,0,c*f,-s,c*d,0,0,0,-3.2,1])}
function frame(t){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.002,.012,.006,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);impulse=Math.max(0,impulse-.018);voice=.16+.12*(.5+.5*Math.sin(t*.003));const out=[];for(let i=0;i<cells;i++){const y=1-(i/(cells-1))*2,r=Math.sqrt(1-y*y),th=golden*i,x=r*Math.cos(th),z=r*Math.sin(th);const wave=.5+.5*Math.sin(th*7-t*.006);const e=.12+Math.pow(wave,10)*Math.max(voice,impulse);const k=1+.035*e;const start=i*12;for(let q=0;q<12;q+=4){const px=verts[start+q],py=verts[start+q+1],pz=verts[start+q+2];out.push(px*k,py*k,pz*k,e);out.push(verts[start+q+4]*k,verts[start+q+5]*k,verts[start+q+6]*k,e)}}gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(out),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(P);gl.vertexAttribPointer(P,3,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(A);gl.vertexAttribPointer(A,1,gl.FLOAT,false,16,12);gl.uniformMatrix4fv(M,false,mat());gl.lineWidth(1);gl.drawArrays(gl.LINES,0,out.length/4);requestAnimationFrame(frame)}requestAnimationFrame(frame);