const canvas=document.getElementById('orb');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
if(!gl){document.body.innerHTML='<p style="padding:24px">WebGL is required for the Hive Orb prototype.</p>';throw new Error('WebGL unavailable');}
const vs=`attribute vec3 p;attribute float a;uniform mat4 mvp;varying float e;void main(){e=a;gl_Position=mvp*vec4(p,1.0);gl_PointSize=2.5+5.0*a;}`;
const fs=`precision mediump float;varying float e;void main(){vec2 q=gl_PointCoord-.5;float d=length(q);float glow=smoothstep(.5,0.0,d);gl_FragColor=vec4(.05,.95,.32,glow*(.35+.65*e));}`;
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);return x}const pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,vs));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(pr);gl.useProgram(pr);
const pts=[];const n=1500;const phi=Math.PI*(3-Math.sqrt(5));for(let i=0;i<n;i++){const y=1-(i/(n-1))*2,r=Math.sqrt(1-y*y),th=phi*i;pts.push(r*Math.cos(th),y,r*Math.sin(th),0.25)}
const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pts),gl.DYNAMIC_DRAW);const P=gl.getAttribLocation(pr,'p'),A=gl.getAttribLocation(pr,'a');gl.enableVertexAttribArray(P);gl.vertexAttribPointer(P,3,gl.FLOAT,false,16,0);gl.enableVertexAttribArray(A);gl.vertexAttribPointer(A,1,gl.FLOAT,false,16,12);const M=gl.getUniformLocation(pr,'mvp');
let rx=.15,ry=0,drag=false,lx=0,ly=0,impulses=[];canvas.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;impulses.push(performance.now())};canvas.onpointerup=()=>drag=false;canvas.onpointermove=e=>{if(drag){ry+=(e.clientX-lx)*.006;rx+=(e.clientY-ly)*.006;lx=e.clientX;ly=e.clientY}};
function mat(){const a=rx,b=ry,c=Math.cos(a),s=Math.sin(a),d=Math.cos(b),f=Math.sin(b);return new Float32Array([d,0,-f,0,s*f,c,s*d,0,c*f,-s,c*d,0,0,0,-3.1,1])}
function frame(t){const w=canvas.width=innerWidth*devicePixelRatio,h=canvas.height=innerHeight*devicePixelRatio;gl.viewport(0,0,w,h);gl.clearColor(.005,.018,.01,1);gl.clear(gl.COLOR_BUFFER_BIT);const e=.35+.65*(.5+.5*Math.sin(t*.006));for(let i=0;i<n;i++){const k=i*4;const wave=0.5+0.5*Math.sin(i*.17-t*.009);pts[k+3]=Math.pow(wave,8)*e}gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferSubData(gl.ARRAY_BUFFER,0,new Float32Array(pts));gl.uniformMatrix4fv(M,false,mat());gl.drawArrays(gl.POINTS,0,n);requestAnimationFrame(frame)}requestAnimationFrame(frame);
